<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-TUFNRNQ" failures="1" tests="1" name="Default test" time="1.806" errors="0" timestamp="2023-07-16T23:23:18 EEST">
  <testcase classname="com.yasen.rest.UserRestAssuredControllerTest" name="deleteUserExistTest" time="1.77">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.game_classes.models.dto.UserDto.getId()&amp;quot; because &amp;quot;foundUser&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.game_classes.models.dto.UserDto.getId()" because "foundUser" is null
at com.yasen.rest.UserRestAssuredControllerTest.deleteUserExistTest(UserRestAssuredControllerTest.java:201)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- deleteUserExistTest -->
  <testcase classname="com.yasen.rest.UserRestAssuredControllerTest" name="deleteUserNotExistTest" time="0.0">
    <ignored/>
  </testcase> <!-- deleteUserNotExistTest -->
  <testcase classname="com.yasen.rest.UserRestAssuredControllerTest" name="getUserNotExistTest" time="0.0">
    <ignored/>
  </testcase> <!-- getUserNotExistTest -->
  <testcase classname="com.yasen.rest.UserRestAssuredControllerTest" name="getUserExistTest" time="0.0">
    <ignored/>
  </testcase> <!-- getUserExistTest -->
  <testcase classname="com.yasen.rest.UserRestAssuredControllerTest" name="getUserTest" time="0.0">
    <ignored/>
  </testcase> <!-- getUserTest -->
  <testcase classname="com.yasen.rest.UserRestAssuredControllerTest" name="updateUserTest" time="0.0">
    <ignored/>
  </testcase> <!-- updateUserTest -->
  <testcase classname="com.yasen.rest.UserRestAssuredControllerTest" name="createUserTest" time="0.0">
    <ignored/>
  </testcase> <!-- createUserTest -->
</testsuite> <!-- Default test -->
